# Generated by Django 4.2.16 on 2025-01-31 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0004_tipoevento_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spam', 'Spam'), ('inapropiado', 'Contenido Inapropiado'), ('ofensivo', 'Contenido Ofensivo'), ('acoso', 'Acoso')], max_length=20)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('desestimada', 'Desestimada')], default='pendiente', max_length=20)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('evento_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='comunicaciones.evento')),
                ('posteo_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='comunicaciones.posteo')),
                ('usuario_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
