# Generated by Django 5.1 on 2024-08-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('numero', models.CharField(max_length=10)),
                ('ocupaDepto', models.BooleanField()),
                ('idDuenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_duenio', to=settings.AUTH_USER_MODEL)),
                ('idOcupante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_ocupante', to=settings.AUTH_USER_MODEL)),
                ('idEdificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='propiedades.edificio')),
            ],
        ),
    ]
