# Generated by Django 5.1 on 2024-08-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0004_remove_user_departamento_user_numero_user_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='ciudad',
            field=models.CharField(default='ciudad por definir', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
