# Generated by Django 5.1 on 2024-08-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        ('usuarios', '0002_user_departamento_user_edificio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ocupantes', to='propiedades.departamento'),
        ),
    ]
