# Generated by Django 5.1 on 2024-08-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departamento',
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
