# Generated by Django 4.2.16 on 2024-11-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0002_edificio_ciudad_alter_edificio_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Plomeria', 'Plomeria'), ('Gasista', 'Gasista'), ('Electricista', 'Electricista'), ('Tecnico en Refrigeracion', 'Tecnico en Refrigeracion'), ('Cerrajero', 'Cerrajero'), ('Pintor', 'Pintor')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='propiedades.edificio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
