# Generated by Django 5.1 on 2024-09-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0002_edificio_ciudad_alter_edificio_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Plomeria', 'Plomeria'), ('Gasista', 'Gasista'), ('Electricista', 'Electricista'), ('Tecnico en Refrigeracion', 'Tecnico en Refrigeracion'), ('Cerrajero', 'Cerrajero'), ('Pintor', 'Pintor')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edificios', models.ManyToManyField(related_name='servicios', to='propiedades.edificio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio')),
            ],
        ),
    ]
